### PR TITLE
Sort by population

### PR DESCRIPTION
**Pull request by exussum12**
Fix for #9

### CODE REVIEW

**Comment by exussum12** [comment]
```
sort -r -k15,15 -t, GB.txt | awk 'BEGIN { FS="\t"; OFS=","; } $8 ~ /^(PPL|ADM)/ && $5 > 49 && $5 < 61 && $6 > -8 && $6 < 2 { gsub(/[^a-zA-Z0-9]/, "", $2); print $8, $2, $5, $6 }' | tr '[:lower:]' '[:upper:]' | sort -u -k2,2 -t, | grep -i newcastle
PPL,LITTLENEWCASTLE,51.92251,-4.93839
PPL,NEWCASTLE,54.21804,-5.88979
ADM3,NEWCASTLEEMLYN,52.03743,-4.45211
ADM3,NEWCASTLEHIGHER,51.53307,-3.60433
ADM3,NEWCASTLEONCLUN,52.45112,-3.12252
PPL,NEWCASTLETON,55.17908,-2.81336
PPL,NEWCASTLEUNDERLYME,53,-2.23333
ADM3,NEWCASTLEUNDERLYMEDISTRICT,52.9946,-2.32455
ADM2,NEWCASTLEUPONTYNE,55,-1.66667
```

Now has the correct one after the unique sort


Edit:

Looking more into this, its chosen another wrong Newcastle

**Comment by exussum12** [comment]
Closing for now. The newcastle that would be expected is in the alias section rather than the full name section. I thought the issue was the unique flag was choosing at random (which it does)

**Comment by beny23** [comment]
Good stuff - I'm still going to implement into the sort, because when choosing PRESTON, it picks Preston, Tyne-and-Weir rather than Preston, Lancs.

**Comment by exussum12** [comment]
Want me to reopen ?

**Comment by beny23** [comment]
My thinking around the Newcastle problem was to 
* when there's a space or `-` in the name (ie. in `Newcastle-upon-Tyne`), add an additional entry with just the bits before the space (i.e. `Newcastle`) to the list
* When that then gets sorted by population it would go for the biggest Newcastle first.

**Comment by exussum12** [comment]
Sounds good.

**Pull request closed without merging**
